.TH "ESELECT" "5" "June 2005" "Gentoo Linux" "eselect"
.SH "NAME"
bashcomp\.eselect \- Manage contributed bash-completion scripts
.SH "SYNOPSIS"
\fBeselect bashcomp\fR [\fBhelp\fR|\fBusage\fR]
.br 
\fBeselect bashcomp\fR \fBlist\fR
.br 
\fBeselect bashcomp\fR \fBenable\fR \fIbashcomp1 bashcomp2\fR
.br 
\fBeselect bashcomp\fR \fBdisable\fR \fIbashcomp1 bashcomp2\fR

.SH "DESCRIPTION"
\fBeselect\fR is Gentoo's configuration and management tool. It features
modules that care for individual administrative tasks.
.SH "ACTION: LIST"
\fBeselect bashcomp list\fR
.br 
Displays a list of available contributed bash-completion scripts.  Enabled
bash-completions are marked with a '*'.

$ eselect bashcomp list
.br 
Available completions:
  [1]  bitkeeper
  [2]  cowsay *
.SH "ACTION: ENABLE"
\fBeselect bashcomp enable \fIbashcomp1 bashcomp2\fR
.br 
Enable the specified completion(s).  Arguments may be a completion name or
a corresponding number produced by \fBeselect bashcomp list\fR.
.SH "ACTION: DISABLE"
\fBeselect bashcomp disable\fR \fIbashcomp1 bashcomp2\fR
.br
Disable the specified completion(s). Arguments may be a completion name or
a corresponding number produced by \fBeselect bashcomp list\fR.
.SH "AUTHORS"
Aaron Walker  <ka0ttic@gentoo.org>
.SH "REVISION"
$Id: profile.eselect.5 117 2005-06-07 06:57:38Z kugelfang $
