.\" Copyright 2006-2009 Gentoo Foundation
.\" Distributed under the terms of the GNU General Public License v2
.\" $Id$
.\"
.TH blas.eselect 5 "April 2009" "Gentoo Linux" eselect
.SH NAME
blas.eselect \- The BLAS management module for Gentoo's eselect
.SH SYNOPSIS
.B eselect blas
.RB [ help | usage | version ]
.br
.B eselect blas list
.RI [ options ]
.br
.B eselect blas add
.br
.B eselect blas set
.I implementation
.RI [ options ]
.br
.B eselect blas show
.RI [ options ]
.SH DESCRIPTION
.B eselect
is Gentoo's configuration and management tool.  It features modules
that care for the individual administrative tasks.
.SH ACTION: LIST
.B eselect blas list
.RI [ options ]
.br
Display an ordered list of installed BLAS implementations.
It distinguishes between versions with different Application Binary
Interfaces (e.g. x86/AMD64).  Furthermore, it also distinguishes
between interfaces to high-level programming languages.  Each line
holds a number and the implementation's name.  An asterisk next to one
of the list elements denotes an active implementation.

# eselect blas list
.br
Installed BLAS for libdir lib
.br
  [1]   atlas *
  [2]   reference

Possible
.I options
to the
.B list
action are restrictions to handle only certain ABI\-specific library
directories. For example,

.B eselect blas list lib64

lists only BLAS implementations found in
.BR /usr/lib64 .

.SH ACTION: SHOW
.B eselect blas show
.RI [ options ]
.br
Show your system's currently active BLAS implementations.

# eselect blas show
.br
lib: atlas
.br
lib64: reference

The same
.I options
that apply to the
.B list
action can be used with the
.B show
action to restrict it to given ABIs.
.SH ACTION: SET
.B eselect blas set
.I implementation
.RI [ options ]
.br
Set your system's currently active BLAS implementations to
.IR implementation .
The same
.I options
that apply to the
.B list
action can be used with the
.B set
action to restrict it to given ABIs.

# eselect blas set atlas
.SH AUTHOR
Danny van Dyk <kugelfang@gentoo.org>
.br
Donnie Berkholz <spyderous@gentoo.org>
.SH SEE ALSO
.BR eselect (1)
.SH REVISION
$Id$
