.\" Copyright 1999-2007 Gentoo Foundation
.\" Distributed under the terms of the GNU General Public License v2
.\" $Id: ctags.eselect.5 620 2007-08-24 13:24:57Z ulm $
.\"
.TH "ESELECT" "5" "August 2007" "Gentoo Linux" "eselect"
.SH "NAME"
ctags.eselect \- The ctags management module for Gentoo's eselect
.SH "SYNOPSIS"
\fBeselect ctags\fR [\fBhelp\fR|\fBusage\fR]
.br
\fBeselect ctags list\fR
.br
\fBeselect ctags set\fR \fItarget\fR
.br
\fBeselect ctags show\fR
.br
\fBeselect ctags update\fR
.SH "DESCRIPTION"
\fBeselect\fR is Gentoo's configuration and management tool. It features
modules that care for the individual administrative tasks.
.SH "ACTION: LIST"
\fBeselect ctags list\fR
.br
List all installed ctags versions.

# eselect ctags list
.br
Available ctags symlink targets:
.br
  [1]   ctags-emacs-22 *
  [2]   exuberant-ctags
.SH "ACTION: SET"
\fBeselect ctags set\fR \fItarget\fR
.br
Activates the selected ctags version. \fItarget\fR can be either an
identification number given by \fBeselect ctags list\fR or the name of
one installed version.

# eselect ctags set 2
.br
Switching to exuberant-ctags ...
.SH "ACTION: SHOW"
\fBeselect ctags show\fR
.br
Prints the currently activated ctags version.

# eselect ctags show
.br
Current target of symlink:
.br
  exuberant-ctags
.SH "ACTION: UPDATE"
\fBeselect ctags update\fR
.br
Update the ctags symlink. For an update only the version is changed,
but not the provider (i.e. Emacs vs Exuberant). At the moment only
(X)Emacs offers several concurrent versions.

# eselect ctags update
.br
Switching to exuberant-ctags ...
.SH "BUGS"
Under FreeBSD, \fBeselect ctags\fR does not work since \fBctags\fR is
a real binary (owned by package freebsd-ubin).
.SH "AUTHOR"
Ulrich Mueller <ulm@gentoo.org>
.SH "SEE ALSO"
.BR eselect (1),
.BR emacs.eselect (5)
.SH "REVISION"
$Id: ctags.eselect.5 620 2007-08-24 13:24:57Z ulm $
