.TH "ESELECT" "1" "April 2005" "Gentoo Linux" "eselect"
.SH "NAME"
\fBeselect\fR \- Gentoo's multi\-purpose configuration and managment tool
.SH "SYNOPSIS"
\fBeselect\fR <\fIglobal options\fR> <\fImodule\fR> <\fImodule options\fR>
.SH "DESCRIPTION"
\fBeselect\fR is Gentoo's configuration and management tool. It features
modules that care for individual administrative tasks.
.SH "OPTIONS"
.B "\-\-no-color, \-\-no-colour"
Disable coloured output.
.SH "BUILT-INS"
.TP
\fIhelp\fR
Displays a help screen listing all built\-ins and the installed modules.
.TP
\fIlist\-modules\fR
Lists only the installed modules.
.TP
\fIusage\fR
Displays a minimal help screen.
.TP
\fIversion\fR
Prints eselect's version tag.
.SH "MODULES"
You can view a list of installed modules using
.ad
.hy
.ad l
.hy 0
.HP 14
\fBeselect\fR \fIlist\-modules\fR
.ad
.hy
.ad l
.hy 0
.HP 14
For individual help on each module, please run
.ad
.hy
.ad l
.hy 0
.HP 14
\fBeselect\fR \fImodule\fR
.ad
.hy
.ad l
.hy 0
.HP 14
or refer to the manpage \fImodule\fR.eselect(5)
.SH "FULL DOCUMENTATION"
Full user and developer documentation is included in Restructured Text (RST)
format. The 'html' Make target can be used to generate HTML versions.
.SH "AUTHORS"
Danny van Dyk <kugelfang@gentoo.org>
.br
Ciaran McCreesh <ciaranm@gentoo.org>
.br
Aaron Walker <ka0ttic@gentoo.org>
.SH "CVS HEADER"
$Id$
