.\" Copyright 2005-2010 Gentoo Foundation
.\" Distributed under the terms of the GNU General Public License v2
.\" $Id$
.\"
.TH kernel.eselect 5 "April 2009" "Gentoo Linux" eselect
.SH NAME
kernel.eselect \- The kernel symlink management module for Gentoo's eselect
.SH SYNOPSIS
.B eselect kernel
.RB [ help | usage | version ]
.br
.B eselect kernel list
.br
.B eselect kernel set
.I target
.br
.B eselect kernel show
.SH DESCRIPTION
.B eselect
is Gentoo's configuration and management tool.  It features modules
that care for the individual administrative tasks.
.SH ACTION: LIST
.B select kernel list
.br
Display an ordered list of available kernels.  An asterisk next to one
of the list elements denotes the currently selected kernel.

# eselect kernel list
.br
Available kernel symlink targets:
  [1]   linux-2.6.11.11
  [2]   linux-2.6.12.5 *
  [3]   linux-2.6.13-rc6
.SH ACTION: SET
.B eselect kernel set
.I target
.br
Set /usr/src/linux symlink to point to the specified kernel name,
.IR target .
The
.I target
argument may be a kernel name or it's associated number (displayed in
.B eselect kernel list
output).
.SH ACTION: SHOW
.B eselect kernel show
.br
Show the currently selected kernel.
.SH AUTHOR
Aaron Walker <ka0ttic@gentoo.org>
.SH SEE ALSO
.BR eselect (1)
.SH REVISION
$Id$
