.\" Copyright 2006-2009 Gentoo Foundation
.\" Distributed under the terms of the GNU General Public License v2
.\" $Id$
.\"
.TH lapack.eselect 5 "May 2009" "Gentoo Linux" eselect
.SH NAME
lapack.eselect \- The LAPACK management module for Gentoo's eselect
.SH SYNOPSIS
.B eselect lapack
.RB [ help | usage | version ]
.br
.B eselect lapack list
.RI [ options ]
.br
.B eselect lapack add
.br
.B eselect lapack set
.I implementation
.RI [ options ]
.br
.B eselect lapack show
.RI [ options ]
.SH DESCRIPTION
.B eselect
is Gentoo's configuration and management tool.  It features modules
that care for the individual administrative tasks.
.SH ACTION: LIST
.B eselect lapack list
.RI [ options ]
.br
Display an ordered list of installed LAPACK implementations.
It distinguishes between versions with different Application Binary
Interfaces (e.g. x86/AMD64).  Furthermore, it also distinguishes
between interfaces to high-level programming languages.  Each line
holds a number and the implementation's name.  An asterisk next to one
of the list elements denotes an active implementation.

# eselect lapack list
.br
Installed LAPACK for libdir lib
.br
  [1]   atlas *
  [2]   reference

Possible
.I options
to the
.B list
action are restrictions to handle only certain ABI\-specific library
directories. For example,

.B eselect lapack list lib64

lists only LAPACK implementations found in
.BR /usr/lib64 .

.SH ACTION: SHOW
.B eselect lapack show
.RI [ options ]
.br
Show your system's currently active LAPACK implementations.

# eselect lapack show
.br
lib: atlas
.br
lib64: reference

The same
.I options
that apply to the
.B list
action can be used with the
.B show
action to restrict it to given ABIs.
.SH ACTION: SET
.B eselect lapack set
.I implementation
.RI [ options ]
.br
Set your system's currently active LAPACK implementations to
.IR implementation .
The same
.I options
that apply to the
.B list
action can be used with the
.B set
action to restrict it to given ABIs.

# eselect lapack set atlas
.SH AUTHOR
Danny van Dyk <kugelfang@gentoo.org>
.br
Donnie Berkholz <dberkholz@gentoo.org>
.SH SEE ALSO
.BR eselect (1)
.SH REVISION
$Id$
