.\" Copyright 2005-2009 Gentoo Foundation
.\" Distributed under the terms of the GNU General Public License v2
.\" $Id$
.\"
.TH mailer.eselect 5 "April 2009" "Gentoo Linux" eselect
.SH NAME
mailer.eselect \- The mailer profile management module for Gentoo's eselect
.SH SYNOPSIS
.B eselect mailer
.RB [ help | usage | version ]
.br
.B eselect mailer list
.br
.B eselect mailer set
.I profile
.br
.B eselect mailer show
.br
.SH DESCRIPTION
.B eselect
is Gentoo's configuration and management tool.  It features modules
that care for the individual administrative tasks.
.SH ACTION: LIST
.B eselect mailer list
.br
Display an ordered list of the installed mailer profiles.  Each line
has a number, the profile's name and version number.

# eselect mailer list
.br
Available mailer.conf profiles:
  [1]   default
  [2]   msmtp\-1.4.0
  [3]   nbsmtp\-0.98
.SH ACTION: SET
.B eselect mailer set
.I profile
.br
Set your system's currently active mailer to
.IR profile .

# eselect mailer set msmtp-1.4.0
.SH ACTION: SHOW
.B eselect mailer show
.br
Show your system's mailer profiles.

# eselect mailer show
.br
Current mailer.conf profile:
  msmtp-1.4.0
.SH AUTHOR
Tom Martin <slarti@gentoo.org>
.SH SEE ALSO
.BR eselect (1)
.SH REVISION
$Id$
