.TH "ESELECT" "5" "April 2005" "Gentoo Linux" "eselect"
.SH "NAME"
mailer.eselect \- The mailer profile management module for Gentoo's eselect
.SH "SYNOPSIS"
\fBeselect mailer\fR [\fBhelp\fR|\fBusage\fR]
.br 
\fBeselect mailer\fR \fBlist\fR
.br 
\fBeselect mailer\fR \fBset\fR \fIprofile\fR
.br 
\fBeselect mailer\fR \fBshow\fR
.br 
.SH "DESCRIPTION"
\fBeselect\fR is Gentoo's configuration and management tool. It features
modules that care for the individual administrative tasks.
.SH "ACTION: LIST"
\fBeselect mailer list\fR [\fIoptions\fR]
.br 
Displays an ordered list of the installed mailer profiles. Each line has
a number, the profile's name and version number.

pohl / # eselect mailer list
.br 
Available mailer.conf profiles:
  [1]   default
  [2]   msmtp\-1.4.0
  [3]   nbsmtp\-0.98
.SH "ACTION: SET"
\fBeselect mailer set\fR \fIprofile\fR
.br 
Sets your system's currently active mailer to \fIprofile\fR. 

pohl / # eselect mailer set msmtp-1.4.0
.SH "ACTION: SHOW"
\fBeselect mailer show\fR
.br 
Shows your system's mailer profiles.

pohl / # eselect mailer show
.br 
Current mailer.conf profile:
  msmtp-1.4.0
.SH "AUTHOR"
Tom Martin <slarti@gentoo.org>
.SH "REVISION"
$Id$
