.\" Copyright 2009 Gentoo Foundation
.\" Distributed under the terms of the GNU General Public License v2
.\" $Id$
.\"
.TH news.eselect 5 "August 2009" "Gentoo Linux" eselect
.SH NAME
news.eselect \- Yet another GLEP 42 news module for Gentoo's eselect
.SH SYNOPSIS
.B eselect news
.RB [ help | usage | version ]
.br
.B eselect news list
.br
.B eselect news read
.RB [ \-\-mbox | \-\-raw ]
.RI [ item ...]
.br
.B eselect news unread
.RI [ item ...]
.br
.B eselect news purge
.br
.B eselect news count
.RB [ new | all ]
.SH DESCRIPTION
.B eselect
is Gentoo's configuration and management tool.  It features modules
that care for the individual administrative tasks.
.SH ACTION: LIST
.B eselect news list
.br
List all Gentoo news items.

# eselect news list
.br
News items:
.br
  [1]   2009-04-18  (unread)  Generation 1 Java Setup Deprecated
  [2]   2009-04-06  (read)    Migration from teTeX to TeXLive
  [3]   2009-04-06  (read)    Migration to X.org Server 1.5
.SH ACTION: READ
.B eselect news read
.RB [ \-\-mbox | \-\-raw ]
.RI [ item ...]
.br
Read news item(s), selected by their
.I item
number(s) from the
.B list
action.  Special items
.B new
and
.B all
select all unread items or all items, respectively.
Default is to read all unread news, if no item is specified.
With options
.B \-\-mbox
or
.BR \-\-raw ,
output the item(s) in mbox format or in raw format, respectively.
.SH ACTION: UNREAD
.B eselect news unread
.RI [ item ...]
.br
Mark news item(s) as unread again.  Items are selected by their
.I item
number(s) from the
.B list
action.  Special item
.B all
selects all items.
.SH ACTION: PURGE
.B eselect news purge
.br
Purge all read news item(s).
.SH ACTION: COUNT
.B eselect news count
.RB [ new | all ]
.br
Display number of unread news items (default) or of all news items,
if option
.B all
is given.
.SH AUTHOR
Ulrich Mueller <ulm@gentoo.org>
.SH SEE ALSO
.BR eselect (1),
http://www.gentoo.org/proj/en/glep/glep-0042.html
.SH REVISION
$Id$
