.\" Copyright 2005-2009 Gentoo Foundation
.\" Distributed under the terms of the GNU General Public License v2
.\" $Id$
.\"
.TH opengl.eselect 5 "April 2009" "Gentoo Linux" eselect
.SH NAME
opengl.eselect \- The OpenGL management module for Gentoo's eselect
.SH SYNOPSIS
.B eselect opengl
.RB [ help | usage | version ]
.br
.B eselect opengl list
.br
.B eselect opengl set
.RI [ options ]
.I implementation
.br
.B eselect opengl show
.SH DESCRIPTION
.B eselect
is Gentoo's configuration and management tool.  It features modules
that care for the individual administrative tasks.
.SH ACTION: LIST
.B eselect opengl list
.br
Display a numbered list of all available OpenGL implementations.
The currently actived implementation is highlighted by a '*'.

# eselect opengl list
.br
Available OpenGL implementations:
  [1]   ati *
  [2]   xfree
  [3]   xorg\-x11
.SH ACTION: SHOW
.B eselect opengl show
.br
Show your system's currently active OpenGL implementation.

# eselect opengl show
.br
ati
.SH ACTION: SET
.B eselect opengl set
.RI [ options ]
.I implementation
.br
Set your system's currently active OpenGL implementation to 
.IR implementation .
.br
Extra options:
.TP
.B \-\-use\-old
If an implementation is already set, use that one.
.TP
.BI \-\-prefix =value
Set the source prefix to
.I value
(defaults to
.BR /usr ).
.TP
.BI \-\-dst\-prefix =value
Set the destination prefix to
.I value
(defaults to
.BR /usr ).
.TP
.B \-\-impl\-headers
Use headers provided by this implementation to override golbal ones
provided by opengl\-update.  This was default in <opengl\-update\-2.2.
.SH AUTHOR
Danny van Dyk <kugelfang@gentoo.org>
.SH SEE ALSO
.BR eselect (1)
.SH REVISION
$Id$
