.TH "ESELECT" "5" "April 2005" "Gentoo Linux" "eselect"
.SH "NAME"
profile\.eselect \- The profile management module for Gentoo's eselect
.SH "SYNOPSIS"
\fBeselect profile\fR [\fBhelp\fR|\fBusage\fR]
.br 
\fBeselect profile\fR \fBlist\fR
.br 
\fBeselect profile\fR \fBset\fR \fIprofile\fR
.br 
\fBeselect profile\fR \fBshow\fR

.SH "DESCRIPTION"
\fBeselect\fR is Gentoo's configuration and management tool. It features
modules that care for the individual administrative tasks.
.SH "ACTION: LIST"
\fBeselect profile list\fR
.br 
Displays an orderd list of available and (for your architecture) valid profiles. 

phi / # eselect profile list
.br 
Available profile symlink targets:
  [1]   default\-linux/amd64/2005.0
.SH "ACTION: SET"
\fBeselect profile\ setup\fR [\fIprofile\fR]
.br 
Select a valid \fIprofile\fR for future use with portage.
.SH "ACTION: SHOW"
\fBeselect profile\ show\fR
.br 
Shows your system's currently active profile.

phi / # eselect profile\ show
.br
Current make.profile symlink:
  /usr/portage/profiles/default\-linux/amd64/2005.0
.SH "AUTHORS"
Danny van Dyk <kugelfang@gentoo.org>
Aaron Walker  <ka0ttic@gentoo.org>
.SH "REVISION"
$Id$
