.\" Copyright 2005-2018 Gentoo Foundation
.\" Distributed under the terms of the GNU GPL version 2 or later
.\"
.TH profile.eselect 5 "April 2009" "Gentoo Linux" eselect
.SH NAME
profile.eselect \- The profile management module for Gentoo's eselect
.SH SYNOPSIS
.B eselect profile
.RB [ help | usage | version ]
.br
.B eselect profile list
.br
.B eselect profile set
.RB [ \-\-force ]
.I profile
.br
.B eselect profile show
.SH DESCRIPTION
.B eselect
is Gentoo's configuration and management tool.  It features modules
that care for the individual administrative tasks.
.SH ACTION: LIST
.B eselect profile list
.br
Display an ordered list of available and (for your architecture) valid
profiles.

# eselect profile list
.br
Available profile symlink targets:
  [1]   default\-linux/amd64/2005.0
.SH ACTION: SET
.B eselect profile set
.RB [ \-\-force ]
.I profile
.br
Select a valid profile for future use with portage.  If the
.B \-\-force
flag is specified, set the profile even if it doesn't appear to be
a valid one (doesn't exist in
.BR ${PORTDIR} /profiles/profiles.desc).
.SH ACTION: SHOW
.B eselect profile show
.br
Show your system's currently active profile.

# eselect profile show
.br
Current make.profile symlink:
  /usr/portage/profiles/default\-linux/amd64/2005.0
.SH AUTHORS
Danny van Dyk <kugelfang@gentoo.org>
.br
Aaron Walker  <ka0ttic@gentoo.org>
.SH SEE ALSO
.BR eselect (1)
