.\" Copyright 2005-2012 Gentoo Foundation
.\" Distributed under the terms of the GNU GPL version 2 or later
.\" $Id$
.\"
.TH rc.eselect 5 "June 2009" "Gentoo Linux" eselect
.SH NAME
rc.eselect \- Runlevel configuration module
.SH SYNOPSIS
.B eselect rc
.RB [ help | usage | version ]
.br
.B eselect rc add
.I script
.RI [ runlevel ...]
.br
.B eselect rc delete
.I script
.RI [ runlevel ...]
.br
.B eselect rc list
.RI [ runlevel ]
.br
.B eselect rc pause
.I script
.RI [ script ...]
.br
.B eselect rc restart
.I script
.RI [ script ...]
.br
.B eselect rc show
.RI [ runlevel ...]
.br
.B eselect rc start
.I script
.RI [ script ...]
.br
.B eselect rc stop
.I script
.RI [ script ...]
.SH DESCRIPTION
.B eselect
is Gentoo's configuration and management tool.  It features modules
that care for the individual administrative tasks.
.SH ACTION: ADD
.B eselect rc add
.I script
.RI [ runlevel ...]
.br
Add
.I script
to given
.IR runlevels .
If no
.I runlevel
is given, this action will add
.I script
to the
.B default
runlevel.

# eselect rc add local default nonetwork notexisting
.br
Adding local to following runlevels
  default                   [done]
  nonetwork                 [skipped]
  notexisting               [invalid]

The result\-tags are as following
.TP
.B [done]
.I script
successfully added to
.IR runlevel .
.TP
.B [failed]
.I script
could not be added to
.IR runlevel .
.TP
.B [skipped]
.I script
already part of
.IR runlevel .
.TP
.B [invalid]
.I runlevel
is not existing.
.SH ACTION: DELETE
.B eselect rc delete
.I script
.RI [ runlevel ...]
.br
Delete
.I script
from given
.IR runlevels .
If no
.I runlevel
is given, this action will delete
.I script
from the
.B default
runlevel.

# eselect rc delete local nonetwork notexisting
.br
Deleting local from following runlevels
  nonetwork                 [done]
  notexisting               [invalid]

The result\-tags are as following
.TP
.B [done]
.I script
successfully deleted from
.I runlevel
.TP
.B [failed]
.I script
could not be deleted from
.IR runlevel .
.TP
.B [skipped]
.I script
not part of
.IR runlevel .
.TP
.B [invalid]
.I runlevel
is not existing.
.SH ACTION: LIST
.B eselect rc list
.RI [ runlevel ]
.br
Display an ordered list of init scripts that belong to
.IR runlevel .
In case that no
.I runlevel
is given, this action will list all scripts from /etc/init.d/.

# eselect rc list default
.br
Init scripts to be started by runlevel default
  cupsd
  local
  metalog
  net.eth0
  netmount
  powernowd
  sshd
  vixie\-cron
  xdm
  xfs
.SH ACTION: PAUSE
.B eselect rc pause
.I script
.RI [ script ...]
.br
Pause the given set of init scripts.

# eselect rc pause net.eth0
.br
 * Stopping eth0
 *   Bringing down eth0
 *     Shutting down eth0 ...
.SH ACTION: RESTART
.B eselect rc restart
.I script
.RI [ script ...]
.br
Restart the given set of init scripts.

# eselect rc restart sshd
.br
Restarting init script
 * ERROR:  "local" has not yet been started.
 * Stopping sshd ...                                            [ ok ]
.SH ACTION: SHOW
.B eselect rc show
.RI [ runlevel ...]
.br
Show init scripts that belong to
.I runlevel
and list them together with their status.  If no
.I runlevel
is given, list the scripts from the current runlevel.
With options
.B --all
or
.B --unused
the scripts of all runlevels or the scripts not assigned to any
runlevel are shown, respectively.

# eselect rc show
.br
Status of init scripts in runlevel "default"
  cupsd                     [started]
  local                     [started]
  metalog                   [started]
  net.eth0                  [started]
  netmount                  [started]
  powernowd                 [started]
  sshd                      [stopped]
  vixie\-cron                [started]
  xdm                       [started]

The status flags are as following
.TP
.B [started]
.I script
has been successfully run.
.TP
.B [stopped]
.I script
has manually been stopped.
.TP
.B [starting]
.I script
is starting.
.TP
.B [stopping]
.I script
stop has been ordered, but it has not ceased yet.
.TP
.B [inactive]
.I script
has started, but is inactive.
.TP
.B [unknown]
.I script
is part of
.IR runlevel ,
but its status is not known.
.SH ACTION: START
.B eselect rc start
.I script
.RI [ script ...]
.br
Starts the given set of init scripts manually, regardless of the
current runlevel.

# eselect rc start local sshd
.br
Restarting init script
 * Starting local ...                                           [ ok ]
 * WARNING:  "sshd" has already been started.
.SH ACTION: STOP
.B eselect rc restart
.I script
.RI [ script ...]
.br
Restarts the given set of init scripts.

# eselect rc restart sshd
.br
Restarting init script
 * ERROR:  "local" has not yet been started.
 * Stopping sshd ...                                            [ ok ]
.SH AUTHOR
Danny van Dyk <kugelfang@gentoo.org>
.SH SEE ALSO
.BR eselect (1)
.SH REVISION
$Id$
