.TH "ECLECTIC" "5" "April 2005" "Gentoo Linux" "eclectic"
.SH "NAME"
eclectic \- Gentoo's multipurpose configuration and managment tool
.SH "SYNOPSIS"
\fBeclectic\fR \fImodule\fR [\fIaction\fR [\fIoption(s)\fR]]
.SH "DESCRIPTION"
\fBeclectic\fR is Gentoo's configuration and management tool. It features
modules that care for the individual administrative tasks.
.SH "BUILT-INS"
.TP 
\fIhelp\fR
Displays a help screen listing all built\-ins and the installed modules.
.TP 
\fIlist\-modules\fR
Lists only the installed modules.
.TP 
\fIusage\fR
Displays a minimal help screen.
.TP 
\fIversion\fR
Prints eclectic's version tag.
.SH "MODULES"
You can view a list of installed modules using
.ad
.hy
.ad l
.hy 0
.HP 14
\fBeclectic list\-modules\fR
.ad
.hy
.ad l
.hy 0
.HP 14
For individual help on each module, please run
.ad
.hy
.ad l
.hy 0
.HP 14
\fBeclectic\fR \fImodule\fR
.ad
.hy
.ad l
.hy 0
.HP 14
or refer to the manpage \fImodule\fR.eclectic
.SH "AUTHOR"
Danny van Dyk <kugelfang@gentoo.org>
.SH "CVS HEADER"
$Id$
